apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phenovar

patchesStrategicMerge:
  - job-adjustments.yml

resources:
  - edge-proxy-env-vars.yml
  - ../../../k8-generic-orchestrations/phenovar/create-databases