apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phenovar

patchesStrategicMerge:
  - redis-data-volume.yml

resources:
  - ../../../k8-generic-orchestrations/phenovar/redis