apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phenovar-ops

patchesStrategicMerge:
  - resources-rclone-volumes.yml

resources:
  - ../../../k8-generic-orchestrations/phenovar/resources-rclone