apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phenovar
namePrefix: troubleshoot-

configMapGenerator:
  - name: phenovar-troubleshoot-client-files
    options:
      disableNameSuffixHash: true
    files:
      - body.json
      - check_status.sh
      - request.sh

patchesStrategicMerge:
  - troubleshoot-addon.yml

resources:
  - ../../../k8-generic-orchestrations/phenovar/client-job