apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phenovar

patchesStrategicMerge:
  - service-adjustments.yml

resources:
  - ingress.yml
  - edge-proxy-env-vars.yml
  - ../../../k8-generic-orchestrations/phenovar/service